sudo: required

services:
  - docker

language: java

script: mvn clean install

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - export IMAGE_NAME=feli6/kafka-consumer-lag-reporter
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME